services:
  postgres:
    container_name: postgres-docker
    image: postgres
    environment:
      POSTGRES_USER: cs_bahadur
      POSTGRES_PASSWORD: Abcd123$
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - local-docker-network
  
  spring-boot-app:
    container_name: spring-demo
    image: spring/demo
    ports:
      - "8080:8080"
    networks:
      - local-docker-network
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  local-docker-network:
    driver: bridge