name: Build and Deploy

on: 
  push:
    branches:
      - develop

jobs:
  buildc-deploy:
    name: Build and Deploy Spring App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERENAME}}/backend:$(date-'%Y-%m-%d%H%-M%-%S')

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERENAME}}
          password: ${{ secrets.DODOCKER_HUB_ACCES_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERENAME}}/backend:$(date-'%Y-%m-%d%H%-M%-%S')
