name: Build and Deploy

on: 
  push:
    branches:
      - develop

jobs:
  buildc-deploy:
    name: Build and Deploy Spring App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/backend:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCES_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/backend:latest

      - name: Deploy the Docker image on EC2 Using SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -v -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME}
            docker stop backend || true
            docker rm backend || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME}}/backend:latest
            docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME}}/backend:latest
